# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QGIS2apiidee
                                 A QGIS plugin
 Complemento que crea un visualizador cartográfico con el contenido del lieno de QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-12-16
        copyright            : (C) 2023 by IngenieroGeomatico
        email                : aurearagon@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QGIS2apiidee class from file QGIS2apiidee.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .QGIS2apiidee import QGIS2apiidee
    return QGIS2apiidee(iface)
